### PR TITLE
Added remove command.

### PR DESCRIPTION
**Pull request by Makefile-dot-in**
Closes issue #7.

### CODE REVIEW

**Comment by AndrewVos** [comment]
This is great thanks !

I do wonder what will happen if a block has a goroutine running 🤔. I actually have no idea tbh.

**Comment by AndrewVos** [comment]
Could you add a paragraph about this to the readme?

**Comment by Makefile-dot-in** [comment]
Done.

**Comment by Makefile-dot-in** [comment]
@AndrewVos Just tested the goroutine thing by removing `title` from the default config, worked as expected.

**Comment by AndrewVos** [comment]
Ah amazing!

**Comment by AndrewVos** [comment]
Ok lgtm. Thanks again.

Ready to merge if you're done?

**Comment by Makefile-dot-in** [comment]
@AndrewVos I'm done.

**Comment by Makefile-dot-in** [comment]
@AndrewVos Could you also close issue #7?

**Comment by AndrewVos** [comment]
Yeah done. Thought it would close automatically

**Pull request merged**
