### PR TITLE
CLI based configuration

### LINKED ISSUE #4: Allow configuring vbar with commands
So you could use bash to create configs?

Some examples:

```bash
vbar --add --left --name "title" --text "Title" --command "get-window-title"

vbar --remove "title"

vbar --update "title"

vbar --replace --left --name "title" --text "Title" --command "get-window-title"

vbar --css --class-name "panel" --css "background-color: red"
vbar --css --class-name "title" --css "background-color: red"

```

### PR DESCRIPTION
**Pull request by AndrewVos**
Closes #4

### CODE REVIEW

**Comment by AndrewVos** [comment]
Example config is in `file.sh`

**Comment by Makefile-dot-in** [comment]
One question: can we have documentation for the D-Bus API as well? And, while we're at it: how about an option to remove blocks and change block properties at runtime?

**Comment by AndrewVos** [comment]
Yeah that sounds like a good idea regarding dbus. I would prefer if people didn't need documentation for it, you know? Make the CLI powerful enough to not need to use dbus.

I'm going to add remove and a way to replace blocks, or insert blocks before / after other blocks. Modifying block properties is maybe not something that would be easy to code.

For example a block may have an interval and a command but then you add a tail_command. What happens in that case? Or the other way around would be perhaps more tricky.

Maybe I should just try it out.

Do you think this PR is worth merging now? I'm using it on my machine and it seems ok.

**Comment by Makefile-dot-in** [comment]
@AndrewVos 

> Yeah that sounds like a good idea regarding dbus. I would prefer if people didn't need documentation for it, you know? Make the CLI powerful enough to not need to use dbus.

I myself write most of my scripts in Python and would prefer not having to use subprocess.

> For example a block may have an interval and a command but then you add a tail_command. What happens in that case? Or the other way around would be perhaps more tricky.

Perharps it would be better adding a type then. Something like

    ./vbar add-block --name block1 --type tail-command --tail-command echo test

> Do you think this PR is worth merging now? I'm using it on my machine and it seems ok.

Yes, IMO.

**Comment by AndrewVos** [comment]
Fair enough! I know barely anything about dbus though so not really sure what I should be writing :/

Ok so I was thinking about types and it would make things a lot easier for the code. Especially the option parsing stuff. I was thinking more of changing the commands like add-block to add-tail-block though.

That way you could change the block parameters but you couldn't change the block type.

**Comment by AndrewVos** [comment]
@Makefile-dot-in merged btw

**Comment by Makefile-dot-in** [comment]
> Ok so I was thinking about types and it would make things a lot easier for the code. Especially the option parsing stuff. I was thinking more of changing the commands like add-block to add-tail-block though.

If it was via a type property, it would be easier to add types in the future. How I imagine it is that there would be a HashMap mapping the names to classes and a widget interface. `command` and `tail-command` would be implemented by putting the common parts of both in one class that implements the interface, and the incommon parts - in a seperate class that would inherit from the first class, in one function, which would be defined in the first class as an abstract function.

**Comment by AndrewVos** [comment]
I can't really think of a use-case for changing block properties at the moment though :thinking:

I mean `text` maybe. But not the others.

**Comment by Makefile-dot-in** [comment]
One I'd imagine is changing modes upon click.

But even if that wasn't the case, it would be useful if we ever add other types of widgets and/or add support for plugins.

**Comment by AndrewVos** [comment]
Yeah true. Ok I'll leave that out for now then, until it's more pressing.

**Pull request merged**
